### ISSUE TITLE
Game doesn't exist

### ISSUE THREAD

**Issue by amanbrar1999** [Redace10/Hubdog#2]
make the game

**Comment by amanbrar1999** [comment]
@Redace10 please take a look at this issue, been open for years

**Comment by Redace10** [comment]
I apologize for this delay. Currently the project for practice-pygame has been temporarily halted and put on the backlog, so I cannot give you an ETA. I apologize for any inconvenience this has caused in your experience.

**Comment by amanbrar1999** [comment]
@Redace10 understandable. I appreciate all of the effort that has been put into this so far, thanks!
